# Generated by Django 5.0 on 2024-01-21 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listingbid_listing_listingcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='staring_bid',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
