# Generated by Django 5.0 on 2024-01-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_staring_bid_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listingbid',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
